- name: Deploy Glance on Ubuntu
  apt:
    name:
      - glance
    state: latest

- name: Configure Glance Database Connection
  replace:
    dest: /etc/glance/glance-api.conf
    regexp: connection = mysql+pymysql://glance:GLANCE_DBPASS@controller/glance
    replace: connection = mysql+pymysql://glance:admin123@controller/glance
    backup: yes

- name: Set Glance Authentication Parameters
  lineinfile:
    dest: /etc/glance/glance-api.conf
    insertafter: '\[keystone_authtoken\]'
    line: "{{ item }}"
    state: present
    backup: yes

  with_items:
    - www_authenticate_uri = http://controller:5000
    - auth_url = http://controller:5000
    - memcached_servers = controller:11211
    - auth_type = password
    - project_domain_name = Default
    - user_domain_name = Default
    - project_name = service
    - username = aaron
    - password = 1

- name: Configure Glance with Keystone for Authentication
  lineinfile:
    dest: /etc/glance/glance-api.conf
    insertafter: '\[paste_deploy\]'
    line: 'flavor = keystone'
    backup: yes

- name: Configure Glance Storage Settings
  lineinfile:
    dest: /etc/glance/glance-api.conf
    insertafter: '\[glance_store\]'
    line: "{{ item }}"
    state: present
    backup: yes

  with_items:
    - stores = file,http
    - default_store = file
    - filesystem_store_datadir = /var/lib/glance/images/

- name: Set Glance Rate Limiting with Oslo Limit
  lineinfile:
    dest: /etc/glance/glance-api.conf
    insertafter: '\[oslo_limit\]'
    line: "{{ item }}"
    state: present
    backup: yes

  with_items:
    - auth_url = http://controller:5000
    - auth_type = password
    - user_domain_id = default
    - username = MY_SERVICE
    - system_scope = all
    - password = MY_PASSWORD
    - endpoint_id = ENDPOINT_ID
    - region_name = RegionOne

- name: Enable Keystone Limits in Glance
  lineinfile:
    dest: /etc/glance/glance-api.conf
    insertafter: '\[DEFAULT\]'
    line: 'use_keystone_limits = True'
    backup: yes

- name: Initialize Glance Database
  shell:
    sudo glance-manage db_sync
