- name: Set Up Nova Components (Ubuntu)
  apt:
    name:
      - nova-api
      - nova-conductor
      - nova-novncproxy
      - nova-scheduler
    state: latest

- name: Configure Nova Database Connection
  lineinfile:
    dest: /etc/nova/nova.conf
    regexp: connection = mysql+pymysql://nova:NOVA_DBPASS@controller/nova_api
    line: connection = mysql+pymysql://nova:admin123@controller/nova_api
    backup: yes
    backrefs: yes

- name: Enable Keystone Authentication for Nova API
  lineinfile:
    dest: /etc/nova/nova.conf
    insertafter: '\[api\]'
    line: 'auth_strategy = keystone'
    state: present
    backup: yes

- name: Configure Nova Database for Keystone Integration
  lineinfile:
    dest: /etc/nova/nova.conf
    regexp: mysql+pymysql://nova:NOVA_DBPASS@controller/nova
    line: mysql+pymysql://nova:admin123@controller/nova
    backup: yes
    backrefs: yes

- name: Set Up Nova Authentication with Keystone
  lineinfile:
    dest: /etc/glance/glance-api.conf
    insertafter: '\[keystone_authtoken\]'
    line: "{{ item }}"
    state: present
    backup: yes
  with_items:
    - www_authenticate_uri = http://controller:5000/
    - auth_url = http://controller:5000/
    - memcached_servers = controller:11211
    - auth_type = password
    - project_domain_name = Default
    - user_domain_name = Default
    - project_name = service
    - username = nova
    - password = admin123

- name: Set Up Nova VNC Settings
  lineinfile:
    dest: /etc/glance/glance-api.conf
    insertafter: '\[vnc\]'
    line: "{{ item }}"
    state: present
    backup: yes
  with_items:
    - enabled = true
    - server_listen = $my_ip
    - server_proxyclient_address = $my_ip

- name: Configure Nova Placement Settings
  lineinfile:
    dest: /etc/glance/glance-api.conf
    insertafter: '\[placement\]'
    line: "{{ item }}"
    state: present
    backup: yes
  with_items:
    - region_name = RegionOne
    - project_domain_name = Default
    - project_name = service
    - auth_type = password
    - user_domain_name = Default
    - auth_url = http://controller:5000/v3
    - username = placement
    - password = admin123

- name: Set Up Nova Default Configuration
  lineinfile:
    dest: /etc/nova/nova.conf
    line: 'my_ip = 10.0.0.11'
    state: present
    backup: yes

- name: Configure Nova Glance API Server
  lineinfile:
    dest: /etc/nova/nova.conf
    line: 'api_server = http://controller:9292'
    state: present
    backup: yes

- name: Configure Nova Concurrency Settings
  lineinfile:
    dest: /etc/nova/nova.conf
    line: 'lock_path = /var/lib/nova/tmp'
    state: present
    backup: yes

- name: Execute Additional Nova Configuration Tasks
  shell:
    cmd: sudo nova-manage api_db sync

- name: Execute Additional Nova Configuration Tasks
  shell:
    cmd: sudo nova-manage cell_v2 map_cell0

- name: Execute Additional Nova Configuration Tasks
  shell:
    cmd: sudo nova-manage db sync

- name: Execute Additional Nova Configuration Tasks
  shell:
    cmd: sudo nova-manage cell_v2 list_cells
